version: 0.2

phases:
  pre_build:
    commands:
      - composer install
      - chmod -R 775 $CODEBUILD_SRC_DIR/dependency-check/bin/console      
  build:
    commands:
      - echo coucou

artifacts:
  files:
    - '**/*'


