version: 0.2

phases:
  pre_build:
    commands:
      - composer install
              
  build:
    commands:
      - echo coucou

artifacts:
  files:
    - '**/*'

files:
  "/var/www/html":
    mode: "000755" 


