version: 0.2

phases:
  pre_build:
    commands:
      - composer install
              
  build:
    commands:
      - echo coucou
      - chmod -R 744 /var/www/html

artifacts:
  files:
    - '**/*'


