<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMjXj6xo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMjXj6xo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMjXj6xo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMjXj6xo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMjXj6xo\App_KernelDevDebugContainer([
    'container.build_hash' => 'MjXj6xo',
    'container.build_id' => '61d78375',
    'container.build_time' => 1637248317,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMjXj6xo');
